name: eliteinapp
version: 1.0.0+1
publish_to: none
description: A new Daring project.
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  get: 4.6.5
  # firebase_messaging: 14.6.1
  flutter_local_notifications: 14.1.0
  # firebase_core: 2.13.0
  connectivity_plus: 4.0.1
  flutter_native_splash: ^2.2.17
  flutter_inappwebview: ^6.0.0-beta.24+1
  url_launcher: 6.1.11
  permission_handler: 10.2.0
  flutter_downloader: 1.10.4
  path_provider: 2.0.15
  http: ^0.13.5
  store_redirect: 2.0.1
  nb_utils: ^5.0.6
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.7.0
  change_app_package_name: ^1.1.0
  open_file_plus: ^3.4.1
  mime: ^1.0.4
  flutter_launcher_icons: ^0.13.1


dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
flutter_native_splash:  
  color: "#FD1F88"
  andriod: true
  ios: true
  andriod_gravity: centre
  fullscreen: true
  image: "assets/images/splash screen.png"
  ios_content_mode: scaleAspectFill
  web: false

flutter:

  uses-material-design: true
  assets:
    - assets/images/
